CREATE TABLE USER
(
    id integer NOT NULL,
    full_name varchar(255) not null,
    primary key(id)
);


CREATE TABLE PLACE (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR, COUNTRY VARCHAR, POPULATION INT);