INSERT INTO USER (id, full_name) VALUES (1, 'jaehyun');
INSERT INTO USER (id, full_name) VALUES (2, 'jinsil');
INSERT INTO USER (id, full_name) VALUES (3, 'nada');

INSERT INTO PLACE (NAME, COUNTRY, POPULATION) VALUES ('San Francisco', 'US', 10000);
INSERT INTO PLACE (NAME, COUNTRY, POPULATION) VALUES ('서울', 'KR', 20000);
INSERT INTO PLACE (NAME, COUNTRY, POPULATION) VALUES ('東京', 'JP', 30000);
INSERT INTO PLACE (NAME, COUNTRY, POPULATION) VALUES ('부산', 'KR', 40000);